/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GraphicsRouteRouteImport } from './routes/graphics/route'
import { Route as GraphicsExampleRouteRouteImport } from './routes/graphics/example/route'
import { Route as GraphicsExampleHtmlRouteRouteImport } from './routes/graphics/example-html/route'
import { Route as GraphicsLaborOfLoveBracketRouteRouteImport } from './routes/graphics/labor-of-love/bracket/route'
import { Route as GraphicsLaborOfLoveLowerThirdRouteRouteImport } from './routes/graphics/labor-of-love/lower-third/route'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GraphicsRouteRoute = GraphicsRouteRouteImport.update({
  id: '/graphics',
  path: '/graphics',
  getParentRoute: () => rootRouteImport,
} as any)
const GraphicsExampleRouteRoute = GraphicsExampleRouteRouteImport.update({
  id: '/example',
  path: '/example',
  getParentRoute: () => GraphicsRouteRoute,
} as any)
const GraphicsExampleHtmlRouteRoute =
  GraphicsExampleHtmlRouteRouteImport.update({
    id: '/example-html',
    path: '/example-html',
    getParentRoute: () => GraphicsRouteRoute,
  } as any)
const GraphicsLaborOfLoveBracketRouteRoute =
  GraphicsLaborOfLoveBracketRouteRouteImport.update({
    id: '/labor-of-love/bracket',
    path: '/labor-of-love/bracket',
    getParentRoute: () => GraphicsRouteRoute,
  } as any)
const GraphicsLaborOfLoveLowerThirdRouteRoute =
  GraphicsLaborOfLoveLowerThirdRouteRouteImport.update({
    id: '/labor-of-love/lower-third',
    path: '/labor-of-love/lower-third',
    getParentRoute: () => GraphicsRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/graphics': typeof GraphicsRouteRouteWithChildren
  '/graphics/example': typeof GraphicsExampleRouteRoute
  '/graphics/example-html': typeof GraphicsExampleHtmlRouteRoute
  '/graphics/labor-of-love/bracket': typeof GraphicsLaborOfLoveBracketRouteRoute
  '/graphics/labor-of-love/lower-third': typeof GraphicsLaborOfLoveLowerThirdRouteRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/graphics': typeof GraphicsRouteRouteWithChildren
  '/graphics/example': typeof GraphicsExampleRouteRoute
  '/graphics/example-html': typeof GraphicsExampleHtmlRouteRoute
  '/graphics/labor-of-love/bracket': typeof GraphicsLaborOfLoveBracketRouteRoute
  '/graphics/labor-of-love/lower-third': typeof GraphicsLaborOfLoveLowerThirdRouteRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/graphics': typeof GraphicsRouteRouteWithChildren
  '/graphics/example': typeof GraphicsExampleRouteRoute
  '/graphics/example-html': typeof GraphicsExampleHtmlRouteRoute
  '/graphics/labor-of-love/bracket': typeof GraphicsLaborOfLoveBracketRouteRoute
  '/graphics/labor-of-love/lower-third': typeof GraphicsLaborOfLoveLowerThirdRouteRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/graphics'
    | '/graphics/example'
    | '/graphics/example-html'
    | '/graphics/labor-of-love/bracket'
    | '/graphics/labor-of-love/lower-third'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/graphics'
    | '/graphics/example'
    | '/graphics/example-html'
    | '/graphics/labor-of-love/bracket'
    | '/graphics/labor-of-love/lower-third'
  id:
    | '__root__'
    | '/'
    | '/graphics'
    | '/graphics/example'
    | '/graphics/example-html'
    | '/graphics/labor-of-love/bracket'
    | '/graphics/labor-of-love/lower-third'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GraphicsRouteRoute: typeof GraphicsRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/graphics': {
      id: '/graphics'
      path: '/graphics'
      fullPath: '/graphics'
      preLoaderRoute: typeof GraphicsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/graphics/example': {
      id: '/graphics/example'
      path: '/example'
      fullPath: '/graphics/example'
      preLoaderRoute: typeof GraphicsExampleRouteRouteImport
      parentRoute: typeof GraphicsRouteRoute
    }
    '/graphics/example-html': {
      id: '/graphics/example-html'
      path: '/example-html'
      fullPath: '/graphics/example-html'
      preLoaderRoute: typeof GraphicsExampleHtmlRouteRouteImport
      parentRoute: typeof GraphicsRouteRoute
    }
    '/graphics/labor-of-love/bracket': {
      id: '/graphics/labor-of-love/bracket'
      path: '/labor-of-love/bracket'
      fullPath: '/graphics/labor-of-love/bracket'
      preLoaderRoute: typeof GraphicsLaborOfLoveBracketRouteRouteImport
      parentRoute: typeof GraphicsRouteRoute
    }
    '/graphics/labor-of-love/lower-third': {
      id: '/graphics/labor-of-love/lower-third'
      path: '/labor-of-love/lower-third'
      fullPath: '/graphics/labor-of-love/lower-third'
      preLoaderRoute: typeof GraphicsLaborOfLoveLowerThirdRouteRouteImport
      parentRoute: typeof GraphicsRouteRoute
    }
  }
}

interface GraphicsRouteRouteChildren {
  GraphicsExampleRouteRoute: typeof GraphicsExampleRouteRoute
  GraphicsExampleHtmlRouteRoute: typeof GraphicsExampleHtmlRouteRoute
  GraphicsLaborOfLoveBracketRouteRoute: typeof GraphicsLaborOfLoveBracketRouteRoute
  GraphicsLaborOfLoveLowerThirdRouteRoute: typeof GraphicsLaborOfLoveLowerThirdRouteRoute
}

const GraphicsRouteRouteChildren: GraphicsRouteRouteChildren = {
  GraphicsExampleRouteRoute: GraphicsExampleRouteRoute,
  GraphicsExampleHtmlRouteRoute: GraphicsExampleHtmlRouteRoute,
  GraphicsLaborOfLoveBracketRouteRoute: GraphicsLaborOfLoveBracketRouteRoute,
  GraphicsLaborOfLoveLowerThirdRouteRoute:
    GraphicsLaborOfLoveLowerThirdRouteRoute,
}

const GraphicsRouteRouteWithChildren = GraphicsRouteRoute._addFileChildren(
  GraphicsRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GraphicsRouteRoute: GraphicsRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
