/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GraphicsRouteRouteImport } from './routes/graphics/route'
import { Route as RenderRundownIdRouteImport } from './routes/render/$rundownId'
import { Route as GraphicsDrexelBasketballScorebugRouteRouteImport } from './routes/graphics/drexel/basketball-scorebug/route'
import { Route as GraphicsLaborOfLoveBracketRouteRouteImport } from './routes/graphics/labor-of-love/bracket/route'
import { Route as GraphicsLaborOfLoveLowerThirdRouteRouteImport } from './routes/graphics/labor-of-love/lower-third/route'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GraphicsRouteRoute = GraphicsRouteRouteImport.update({
  id: '/graphics',
  path: '/graphics',
  getParentRoute: () => rootRouteImport,
} as any)
const RenderRundownIdRoute = RenderRundownIdRouteImport.update({
  id: '/render/$rundownId',
  path: '/render/$rundownId',
  getParentRoute: () => rootRouteImport,
} as any)
const GraphicsDrexelBasketballScorebugRouteRoute =
  GraphicsDrexelBasketballScorebugRouteRouteImport.update({
    id: '/drexel/basketball-scorebug',
    path: '/drexel/basketball-scorebug',
    getParentRoute: () => GraphicsRouteRoute,
  } as any)
const GraphicsLaborOfLoveBracketRouteRoute =
  GraphicsLaborOfLoveBracketRouteRouteImport.update({
    id: '/labor-of-love/bracket',
    path: '/labor-of-love/bracket',
    getParentRoute: () => GraphicsRouteRoute,
  } as any)
const GraphicsLaborOfLoveLowerThirdRouteRoute =
  GraphicsLaborOfLoveLowerThirdRouteRouteImport.update({
    id: '/labor-of-love/lower-third',
    path: '/labor-of-love/lower-third',
    getParentRoute: () => GraphicsRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/graphics': typeof GraphicsRouteRouteWithChildren
  '/render/$rundownId': typeof RenderRundownIdRoute
  '/graphics/drexel/basketball-scorebug': typeof GraphicsDrexelBasketballScorebugRouteRoute
  '/graphics/labor-of-love/bracket': typeof GraphicsLaborOfLoveBracketRouteRoute
  '/graphics/labor-of-love/lower-third': typeof GraphicsLaborOfLoveLowerThirdRouteRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/graphics': typeof GraphicsRouteRouteWithChildren
  '/render/$rundownId': typeof RenderRundownIdRoute
  '/graphics/drexel/basketball-scorebug': typeof GraphicsDrexelBasketballScorebugRouteRoute
  '/graphics/labor-of-love/bracket': typeof GraphicsLaborOfLoveBracketRouteRoute
  '/graphics/labor-of-love/lower-third': typeof GraphicsLaborOfLoveLowerThirdRouteRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/graphics': typeof GraphicsRouteRouteWithChildren
  '/render/$rundownId': typeof RenderRundownIdRoute
  '/graphics/drexel/basketball-scorebug': typeof GraphicsDrexelBasketballScorebugRouteRoute
  '/graphics/labor-of-love/bracket': typeof GraphicsLaborOfLoveBracketRouteRoute
  '/graphics/labor-of-love/lower-third': typeof GraphicsLaborOfLoveLowerThirdRouteRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/graphics'
    | '/render/$rundownId'
    | '/graphics/drexel/basketball-scorebug'
    | '/graphics/labor-of-love/bracket'
    | '/graphics/labor-of-love/lower-third'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/graphics'
    | '/render/$rundownId'
    | '/graphics/drexel/basketball-scorebug'
    | '/graphics/labor-of-love/bracket'
    | '/graphics/labor-of-love/lower-third'
  id:
    | '__root__'
    | '/'
    | '/graphics'
    | '/render/$rundownId'
    | '/graphics/drexel/basketball-scorebug'
    | '/graphics/labor-of-love/bracket'
    | '/graphics/labor-of-love/lower-third'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GraphicsRouteRoute: typeof GraphicsRouteRouteWithChildren
  RenderRundownIdRoute: typeof RenderRundownIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/graphics': {
      id: '/graphics'
      path: '/graphics'
      fullPath: '/graphics'
      preLoaderRoute: typeof GraphicsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/render/$rundownId': {
      id: '/render/$rundownId'
      path: '/render/$rundownId'
      fullPath: '/render/$rundownId'
      preLoaderRoute: typeof RenderRundownIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/graphics/drexel/basketball-scorebug': {
      id: '/graphics/drexel/basketball-scorebug'
      path: '/drexel/basketball-scorebug'
      fullPath: '/graphics/drexel/basketball-scorebug'
      preLoaderRoute: typeof GraphicsDrexelBasketballScorebugRouteRouteImport
      parentRoute: typeof GraphicsRouteRoute
    }
    '/graphics/labor-of-love/bracket': {
      id: '/graphics/labor-of-love/bracket'
      path: '/labor-of-love/bracket'
      fullPath: '/graphics/labor-of-love/bracket'
      preLoaderRoute: typeof GraphicsLaborOfLoveBracketRouteRouteImport
      parentRoute: typeof GraphicsRouteRoute
    }
    '/graphics/labor-of-love/lower-third': {
      id: '/graphics/labor-of-love/lower-third'
      path: '/labor-of-love/lower-third'
      fullPath: '/graphics/labor-of-love/lower-third'
      preLoaderRoute: typeof GraphicsLaborOfLoveLowerThirdRouteRouteImport
      parentRoute: typeof GraphicsRouteRoute
    }
  }
}

interface GraphicsRouteRouteChildren {
  GraphicsDrexelBasketballScorebugRouteRoute: typeof GraphicsDrexelBasketballScorebugRouteRoute
  GraphicsLaborOfLoveBracketRouteRoute: typeof GraphicsLaborOfLoveBracketRouteRoute
  GraphicsLaborOfLoveLowerThirdRouteRoute: typeof GraphicsLaborOfLoveLowerThirdRouteRoute
}

const GraphicsRouteRouteChildren: GraphicsRouteRouteChildren = {
  GraphicsDrexelBasketballScorebugRouteRoute:
    GraphicsDrexelBasketballScorebugRouteRoute,
  GraphicsLaborOfLoveBracketRouteRoute: GraphicsLaborOfLoveBracketRouteRoute,
  GraphicsLaborOfLoveLowerThirdRouteRoute:
    GraphicsLaborOfLoveLowerThirdRouteRoute,
}

const GraphicsRouteRouteWithChildren = GraphicsRouteRoute._addFileChildren(
  GraphicsRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GraphicsRouteRoute: GraphicsRouteRouteWithChildren,
  RenderRundownIdRoute: RenderRundownIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
