/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ControlRouteRouteImport } from './routes/control/route'
import { Route as GraphicsRouteRouteImport } from './routes/graphics/route'
import { Route as ControlIndexRouteImport } from './routes/control/index'
import { Route as ControlRundownIdRouteRouteImport } from './routes/control/$rundownId/route'
import { Route as ControlPackagesRouteImport } from './routes/control/packages'
import { Route as RenderIndexRouteImport } from './routes/render/index'
import { Route as RenderRundownIdRouteImport } from './routes/render/$rundownId'
import { Route as ControlRundownIdIndexRouteImport } from './routes/control/$rundownId/index'
import { Route as ControlRundownIdPackagesRouteImport } from './routes/control/$rundownId/packages'
import { Route as ControlRundownIdRenderersRouteImport } from './routes/control/$rundownId/renderers'
import { Route as ControlRundownIdTemplatesRouteImport } from './routes/control/$rundownId/templates'
import { Route as GraphicsDrexelBasketballScorebugRouteRouteImport } from './routes/graphics/drexel/basketball-scorebug/route'
import { Route as GraphicsLaborOfLoveBracketRouteRouteImport } from './routes/graphics/labor-of-love/bracket/route'
import { Route as GraphicsLaborOfLoveLowerThirdRouteRouteImport } from './routes/graphics/labor-of-love/lower-third/route'
import { Route as GraphicsPSplatRouteImport } from './routes/graphics/p/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ControlRouteRoute = ControlRouteRouteImport.update({
  id: '/control',
  path: '/control',
  getParentRoute: () => rootRouteImport,
} as any)
const GraphicsRouteRoute = GraphicsRouteRouteImport.update({
  id: '/graphics',
  path: '/graphics',
  getParentRoute: () => rootRouteImport,
} as any)
const ControlIndexRoute = ControlIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ControlRouteRoute,
} as any)
const ControlRundownIdRouteRoute = ControlRundownIdRouteRouteImport.update({
  id: '/$rundownId',
  path: '/$rundownId',
  getParentRoute: () => ControlRouteRoute,
} as any)
const ControlPackagesRoute = ControlPackagesRouteImport.update({
  id: '/packages',
  path: '/packages',
  getParentRoute: () => ControlRouteRoute,
} as any)
const RenderIndexRoute = RenderIndexRouteImport.update({
  id: '/render/',
  path: '/render/',
  getParentRoute: () => rootRouteImport,
} as any)
const RenderRundownIdRoute = RenderRundownIdRouteImport.update({
  id: '/render/$rundownId',
  path: '/render/$rundownId',
  getParentRoute: () => rootRouteImport,
} as any)
const ControlRundownIdIndexRoute = ControlRundownIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ControlRundownIdRouteRoute,
} as any)
const ControlRundownIdPackagesRoute =
  ControlRundownIdPackagesRouteImport.update({
    id: '/packages',
    path: '/packages',
    getParentRoute: () => ControlRundownIdRouteRoute,
  } as any)
const ControlRundownIdRenderersRoute =
  ControlRundownIdRenderersRouteImport.update({
    id: '/renderers',
    path: '/renderers',
    getParentRoute: () => ControlRundownIdRouteRoute,
  } as any)
const ControlRundownIdTemplatesRoute =
  ControlRundownIdTemplatesRouteImport.update({
    id: '/templates',
    path: '/templates',
    getParentRoute: () => ControlRundownIdRouteRoute,
  } as any)
const GraphicsDrexelBasketballScorebugRouteRoute =
  GraphicsDrexelBasketballScorebugRouteRouteImport.update({
    id: '/drexel/basketball-scorebug',
    path: '/drexel/basketball-scorebug',
    getParentRoute: () => GraphicsRouteRoute,
  } as any)
const GraphicsLaborOfLoveBracketRouteRoute =
  GraphicsLaborOfLoveBracketRouteRouteImport.update({
    id: '/labor-of-love/bracket',
    path: '/labor-of-love/bracket',
    getParentRoute: () => GraphicsRouteRoute,
  } as any)
const GraphicsLaborOfLoveLowerThirdRouteRoute =
  GraphicsLaborOfLoveLowerThirdRouteRouteImport.update({
    id: '/labor-of-love/lower-third',
    path: '/labor-of-love/lower-third',
    getParentRoute: () => GraphicsRouteRoute,
  } as any)
const GraphicsPSplatRoute = GraphicsPSplatRouteImport.update({
  id: '/p/$',
  path: '/p/$',
  getParentRoute: () => GraphicsRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/control': typeof ControlRouteRouteWithChildren
  '/graphics': typeof GraphicsRouteRouteWithChildren
  '/control/$rundownId': typeof ControlRundownIdRouteRouteWithChildren
  '/control/packages': typeof ControlPackagesRoute
  '/render/$rundownId': typeof RenderRundownIdRoute
  '/control/': typeof ControlIndexRoute
  '/render/': typeof RenderIndexRoute
  '/graphics/drexel/basketball-scorebug': typeof GraphicsDrexelBasketballScorebugRouteRoute
  '/graphics/labor-of-love/bracket': typeof GraphicsLaborOfLoveBracketRouteRoute
  '/graphics/labor-of-love/lower-third': typeof GraphicsLaborOfLoveLowerThirdRouteRoute
  '/control/$rundownId/packages': typeof ControlRundownIdPackagesRoute
  '/control/$rundownId/renderers': typeof ControlRundownIdRenderersRoute
  '/control/$rundownId/templates': typeof ControlRundownIdTemplatesRoute
  '/graphics/p/$': typeof GraphicsPSplatRoute
  '/control/$rundownId/': typeof ControlRundownIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/graphics': typeof GraphicsRouteRouteWithChildren
  '/control/packages': typeof ControlPackagesRoute
  '/render/$rundownId': typeof RenderRundownIdRoute
  '/control': typeof ControlIndexRoute
  '/render': typeof RenderIndexRoute
  '/graphics/drexel/basketball-scorebug': typeof GraphicsDrexelBasketballScorebugRouteRoute
  '/graphics/labor-of-love/bracket': typeof GraphicsLaborOfLoveBracketRouteRoute
  '/graphics/labor-of-love/lower-third': typeof GraphicsLaborOfLoveLowerThirdRouteRoute
  '/control/$rundownId/packages': typeof ControlRundownIdPackagesRoute
  '/control/$rundownId/renderers': typeof ControlRundownIdRenderersRoute
  '/control/$rundownId/templates': typeof ControlRundownIdTemplatesRoute
  '/graphics/p/$': typeof GraphicsPSplatRoute
  '/control/$rundownId': typeof ControlRundownIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/control': typeof ControlRouteRouteWithChildren
  '/graphics': typeof GraphicsRouteRouteWithChildren
  '/control/$rundownId': typeof ControlRundownIdRouteRouteWithChildren
  '/control/packages': typeof ControlPackagesRoute
  '/render/$rundownId': typeof RenderRundownIdRoute
  '/control/': typeof ControlIndexRoute
  '/render/': typeof RenderIndexRoute
  '/graphics/drexel/basketball-scorebug': typeof GraphicsDrexelBasketballScorebugRouteRoute
  '/graphics/labor-of-love/bracket': typeof GraphicsLaborOfLoveBracketRouteRoute
  '/graphics/labor-of-love/lower-third': typeof GraphicsLaborOfLoveLowerThirdRouteRoute
  '/control/$rundownId/packages': typeof ControlRundownIdPackagesRoute
  '/control/$rundownId/renderers': typeof ControlRundownIdRenderersRoute
  '/control/$rundownId/templates': typeof ControlRundownIdTemplatesRoute
  '/graphics/p/$': typeof GraphicsPSplatRoute
  '/control/$rundownId/': typeof ControlRundownIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/control'
    | '/graphics'
    | '/control/$rundownId'
    | '/control/packages'
    | '/render/$rundownId'
    | '/control/'
    | '/render/'
    | '/graphics/drexel/basketball-scorebug'
    | '/graphics/labor-of-love/bracket'
    | '/graphics/labor-of-love/lower-third'
    | '/control/$rundownId/packages'
    | '/control/$rundownId/renderers'
    | '/control/$rundownId/templates'
    | '/graphics/p/$'
    | '/control/$rundownId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/graphics'
    | '/control/packages'
    | '/render/$rundownId'
    | '/control'
    | '/render'
    | '/graphics/drexel/basketball-scorebug'
    | '/graphics/labor-of-love/bracket'
    | '/graphics/labor-of-love/lower-third'
    | '/control/$rundownId/packages'
    | '/control/$rundownId/renderers'
    | '/control/$rundownId/templates'
    | '/graphics/p/$'
    | '/control/$rundownId'
  id:
    | '__root__'
    | '/'
    | '/control'
    | '/graphics'
    | '/control/$rundownId'
    | '/control/packages'
    | '/render/$rundownId'
    | '/control/'
    | '/render/'
    | '/graphics/drexel/basketball-scorebug'
    | '/graphics/labor-of-love/bracket'
    | '/graphics/labor-of-love/lower-third'
    | '/control/$rundownId/packages'
    | '/control/$rundownId/renderers'
    | '/control/$rundownId/templates'
    | '/graphics/p/$'
    | '/control/$rundownId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ControlRouteRoute: typeof ControlRouteRouteWithChildren
  GraphicsRouteRoute: typeof GraphicsRouteRouteWithChildren
  RenderRundownIdRoute: typeof RenderRundownIdRoute
  RenderIndexRoute: typeof RenderIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/control': {
      id: '/control'
      path: '/control'
      fullPath: '/control'
      preLoaderRoute: typeof ControlRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/graphics': {
      id: '/graphics'
      path: '/graphics'
      fullPath: '/graphics'
      preLoaderRoute: typeof GraphicsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/control/': {
      id: '/control/'
      path: '/'
      fullPath: '/control/'
      preLoaderRoute: typeof ControlIndexRouteImport
      parentRoute: typeof ControlRouteRoute
    }
    '/control/$rundownId': {
      id: '/control/$rundownId'
      path: '/$rundownId'
      fullPath: '/control/$rundownId'
      preLoaderRoute: typeof ControlRundownIdRouteRouteImport
      parentRoute: typeof ControlRouteRoute
    }
    '/control/packages': {
      id: '/control/packages'
      path: '/packages'
      fullPath: '/control/packages'
      preLoaderRoute: typeof ControlPackagesRouteImport
      parentRoute: typeof ControlRouteRoute
    }
    '/render/': {
      id: '/render/'
      path: '/render'
      fullPath: '/render/'
      preLoaderRoute: typeof RenderIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/render/$rundownId': {
      id: '/render/$rundownId'
      path: '/render/$rundownId'
      fullPath: '/render/$rundownId'
      preLoaderRoute: typeof RenderRundownIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/control/$rundownId/': {
      id: '/control/$rundownId/'
      path: '/'
      fullPath: '/control/$rundownId/'
      preLoaderRoute: typeof ControlRundownIdIndexRouteImport
      parentRoute: typeof ControlRundownIdRouteRoute
    }
    '/control/$rundownId/packages': {
      id: '/control/$rundownId/packages'
      path: '/packages'
      fullPath: '/control/$rundownId/packages'
      preLoaderRoute: typeof ControlRundownIdPackagesRouteImport
      parentRoute: typeof ControlRundownIdRouteRoute
    }
    '/control/$rundownId/renderers': {
      id: '/control/$rundownId/renderers'
      path: '/renderers'
      fullPath: '/control/$rundownId/renderers'
      preLoaderRoute: typeof ControlRundownIdRenderersRouteImport
      parentRoute: typeof ControlRundownIdRouteRoute
    }
    '/control/$rundownId/templates': {
      id: '/control/$rundownId/templates'
      path: '/templates'
      fullPath: '/control/$rundownId/templates'
      preLoaderRoute: typeof ControlRundownIdTemplatesRouteImport
      parentRoute: typeof ControlRundownIdRouteRoute
    }
    '/graphics/drexel/basketball-scorebug': {
      id: '/graphics/drexel/basketball-scorebug'
      path: '/drexel/basketball-scorebug'
      fullPath: '/graphics/drexel/basketball-scorebug'
      preLoaderRoute: typeof GraphicsDrexelBasketballScorebugRouteRouteImport
      parentRoute: typeof GraphicsRouteRoute
    }
    '/graphics/labor-of-love/bracket': {
      id: '/graphics/labor-of-love/bracket'
      path: '/labor-of-love/bracket'
      fullPath: '/graphics/labor-of-love/bracket'
      preLoaderRoute: typeof GraphicsLaborOfLoveBracketRouteRouteImport
      parentRoute: typeof GraphicsRouteRoute
    }
    '/graphics/labor-of-love/lower-third': {
      id: '/graphics/labor-of-love/lower-third'
      path: '/labor-of-love/lower-third'
      fullPath: '/graphics/labor-of-love/lower-third'
      preLoaderRoute: typeof GraphicsLaborOfLoveLowerThirdRouteRouteImport
      parentRoute: typeof GraphicsRouteRoute
    }
    '/graphics/p/$': {
      id: '/graphics/p/$'
      path: '/p/$'
      fullPath: '/graphics/p/$'
      preLoaderRoute: typeof GraphicsPSplatRouteImport
      parentRoute: typeof GraphicsRouteRoute
    }
  }
}

interface ControlRundownIdRouteRouteChildren {
  ControlRundownIdPackagesRoute: typeof ControlRundownIdPackagesRoute
  ControlRundownIdRenderersRoute: typeof ControlRundownIdRenderersRoute
  ControlRundownIdTemplatesRoute: typeof ControlRundownIdTemplatesRoute
  ControlRundownIdIndexRoute: typeof ControlRundownIdIndexRoute
}

const ControlRundownIdRouteRouteChildren: ControlRundownIdRouteRouteChildren = {
  ControlRundownIdPackagesRoute: ControlRundownIdPackagesRoute,
  ControlRundownIdRenderersRoute: ControlRundownIdRenderersRoute,
  ControlRundownIdTemplatesRoute: ControlRundownIdTemplatesRoute,
  ControlRundownIdIndexRoute: ControlRundownIdIndexRoute,
}

const ControlRundownIdRouteRouteWithChildren =
  ControlRundownIdRouteRoute._addFileChildren(
    ControlRundownIdRouteRouteChildren,
  )

interface ControlRouteRouteChildren {
  ControlRundownIdRouteRoute: typeof ControlRundownIdRouteRouteWithChildren
  ControlPackagesRoute: typeof ControlPackagesRoute
  ControlIndexRoute: typeof ControlIndexRoute
}

const ControlRouteRouteChildren: ControlRouteRouteChildren = {
  ControlRundownIdRouteRoute: ControlRundownIdRouteRouteWithChildren,
  ControlPackagesRoute: ControlPackagesRoute,
  ControlIndexRoute: ControlIndexRoute,
}

const ControlRouteRouteWithChildren = ControlRouteRoute._addFileChildren(
  ControlRouteRouteChildren,
)

interface GraphicsRouteRouteChildren {
  GraphicsDrexelBasketballScorebugRouteRoute: typeof GraphicsDrexelBasketballScorebugRouteRoute
  GraphicsLaborOfLoveBracketRouteRoute: typeof GraphicsLaborOfLoveBracketRouteRoute
  GraphicsLaborOfLoveLowerThirdRouteRoute: typeof GraphicsLaborOfLoveLowerThirdRouteRoute
  GraphicsPSplatRoute: typeof GraphicsPSplatRoute
}

const GraphicsRouteRouteChildren: GraphicsRouteRouteChildren = {
  GraphicsDrexelBasketballScorebugRouteRoute:
    GraphicsDrexelBasketballScorebugRouteRoute,
  GraphicsLaborOfLoveBracketRouteRoute: GraphicsLaborOfLoveBracketRouteRoute,
  GraphicsLaborOfLoveLowerThirdRouteRoute:
    GraphicsLaborOfLoveLowerThirdRouteRoute,
  GraphicsPSplatRoute: GraphicsPSplatRoute,
}

const GraphicsRouteRouteWithChildren = GraphicsRouteRoute._addFileChildren(
  GraphicsRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ControlRouteRoute: ControlRouteRouteWithChildren,
  GraphicsRouteRoute: GraphicsRouteRouteWithChildren,
  RenderRundownIdRoute: RenderRundownIdRoute,
  RenderIndexRoute: RenderIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
